name: Issue triage

on:
  issues:
    types: [opened]
  issue_comment: 
    types: [created, edited]


permissions:
  issues: write

jobs: 
  assignLabel: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Triage issue
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/triageIssue.js');
            await script({ github, context });
